### ISSUE TITLE
Not 1, but 2 IIIF images. Whoah there...

### ISSUE THREAD

**Issue by IrisBox** [FitzwilliamMuseum/walking-the-landscape-fitz-cdh#5]
Is it possible to add two embedded IIIF images at different points in the text? 
Not Critical, example is here (have put "!Manifest ..." in-line where they would ideally go)
https://walking-the-landscape.fitzmuseum.cam.ac.uk/blog/printedlandscape/

**Comment by portableant** [comment]
Simplest way will be to copy the code below:

`<iframe src="https://fitzmuseum.cam.ac.uk/uv.html#?manifest={{ page.manifest }}&c=0&m=0&cv=0&config=&locales=en-GB:English (GB),cy-GB:Cymraeg,fr-FR:Français (FR),pl-PL:Polski,sv-SE:Svenska&r=0" width="100%" height="600" allowfullscreen frameborder="0"></iframe>`

Then replace the {{page.manifest}} part with your manifest url or add front matter keys like: manifest one: manifestUrl and in the code replace the variable with {{post.manifestOne}} etc it's post in this case as you're interaction is at post level

**Comment by portableant** [comment]
Closed in caa05e57f6d3032090fef43ee7e4f0a6124f78cc
